[build]
    functions = "functions/"
    publish = "build"

[dev]
    functions =  "functions/"
    publish = "build"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200