export { default as Homepage } from "./Homepage/Homepage";
export { default as Sidebar } from "./Sidebar/Sidebar";
export { default as News } from "./News/News";
export { default as Cryptocurrencies } from "./Cryptocurrencies/Cryptocurrencies";
export { default as CryptoDetails } from "./CryptoDetails/CryptoDetails";
export { default as Exchanges } from "./Exchanges/Exchanges";
export { default as Footer } from "./Footer/Footer";
export { default as RoutesMenu } from "./RoutesMenu/RoutesMenu";
export { default as StatsComponent } from "./Stats/Stats";
